# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='expenses/'),
        ),
    ]
